{
 "title": "HTTP Requests Rate",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" },
    { "expr": "redis_connected_clients", "legendFormat": "__auto" },
    { "expr": "pg_stat_activity_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(http_request_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate (% попаданий в кэш)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  rate(redis_cache_hits_total[5m])\n/\nclamp_min(\n  rate(redis_cache_hits_total[5m]) +\n  rate(redis_cache_misses_total[5m]),\n  1\n)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}